export const productTypes = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  FILTER_PRODUCTS_BY_SIZE: "FILTER_PRODUCTS_BY_SIZE",
  ORDER_PRODUCTS_BY_PRICE: "ORDER_PRODUCTS_BY_PRICE",
};

export const cartTypes = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
};

export const orderTypes = {
  CREATE_ORDER: "CREATE_ORDER",
  CLEAR_ORDER: "CLEAR_ORDER",
  CLEAR_CART: "CLEAR_CART",
};
